INSERT INTO m_lib_mc_risk_factors VALUES (1,'N','','Age younger than 15 years old or older than 35 years old.');
INSERT INTO m_lib_mc_risk_factors VALUES (2,'N','','Height lower than 145cm.');
INSERT INTO m_lib_mc_risk_factors VALUES (3,'Y','','Poor OB history (3 consecutive miscarriages, stillbirth, postpartum hemorrhage)');
INSERT INTO m_lib_mc_risk_factors VALUES (4,'N','','Leg and pelvic deformities (polio paralysis)');
INSERT INTO m_lib_mc_risk_factors VALUES (5,'N','','No prenatal or irregular prenatal in previous pregnancy');
INSERT INTO m_lib_mc_risk_factors VALUES (6,'N','','First pregnancy');
INSERT INTO m_lib_mc_risk_factors VALUES (7,'N','','Pregnancy more than 5');
INSERT INTO m_lib_mc_risk_factors VALUES (8,'N','','Pregnancy interval less than 24 months from the last delivery');
INSERT INTO m_lib_mc_risk_factors VALUES (9,'N','','Pregnancy longer than 294 days or 42 weeks');
INSERT INTO m_lib_mc_risk_factors VALUES (10,'N','','Pre-pregnancy weight less than 80% of standard weight');
INSERT INTO m_lib_mc_risk_factors VALUES (11,'N','Y','Anemia less than 8gm Hb');
INSERT INTO m_lib_mc_risk_factors VALUES (12,'N','Y','Weight less than 4% of pre-pregnancy weight per trimester');
INSERT INTO m_lib_mc_risk_factors VALUES (13,'N','Y','Weight gain more than 6% of pre-pregnancy weight per trimester');
INSERT INTO m_lib_mc_risk_factors VALUES (14,'N','','Abnormal presentation');
INSERT INTO m_lib_mc_risk_factors VALUES (15,'N','','Multiple fetus');
INSERT INTO m_lib_mc_risk_factors VALUES (16,'N','','Blood pressure greater than 140/90');
INSERT INTO m_lib_mc_risk_factors VALUES (17,'N','','Dizziness or blurring of vision');
INSERT INTO m_lib_mc_risk_factors VALUES (18,'N','','Convulsions');
INSERT INTO m_lib_mc_risk_factors VALUES (19,'N','','Positive urine albumin');
INSERT INTO m_lib_mc_risk_factors VALUES (20,'N','','Vaginal infections');
INSERT INTO m_lib_mc_risk_factors VALUES (21,'N','','Vaginal bleeding');
INSERT INTO m_lib_mc_risk_factors VALUES (22,'N','','Pitting edema');
INSERT INTO m_lib_mc_risk_factors VALUES (23,'Y','','Heart or kidney disease');
INSERT INTO m_lib_mc_risk_factors VALUES (24,'N','','Tuberculosis');
INSERT INTO m_lib_mc_risk_factors VALUES (25,'N','','Malaria');
INSERT INTO m_lib_mc_risk_factors VALUES (26,'Y','','Diabetes');
INSERT INTO m_lib_mc_risk_factors VALUES (27,'N','','Rubella');
INSERT INTO m_lib_mc_risk_factors VALUES (28,'Y','','Thyroid problems');
INSERT INTO m_lib_mc_risk_factors VALUES (30,'N','','Mental disorder');
INSERT INTO m_lib_mc_risk_factors VALUES (31,'N','','Unwed mother');
INSERT INTO m_lib_mc_risk_factors VALUES (32,'N','','Illiterate mother');
INSERT INTO m_lib_mc_risk_factors VALUES (33,'N','','Perform heavy manual labor');
INSERT INTO m_lib_mc_risk_factors VALUES (34,'N','','Unwanted or unplanned pregnancy');
INSERT INTO m_lib_mc_risk_factors VALUES (35,'N','','Other socio-economic factors');
INSERT INTO m_lib_mc_risk_factors VALUES (36,'Y','','previous cesarean section');
INSERT INTO m_lib_mc_risk_factors VALUES (37,'Y','','Bronchial asthma');
